import type { Metadata } from "next";
import { Prose } from "@/components/SiteChrome";

export const metadata: Metadata = {
  title: "Support — FURAB",
  description:
    "Get help with FURAB — report a problem, request a tracker, or ask about syncing.",
};

export default function Contact() {
  return (
    <Prose title="Support">
      <p>
        FURAB is made by one person for tired parents. If something is broken or
        missing, writing in genuinely changes what gets built next.
      </p>

      <h2>Get in touch</h2>
      <p>
        Email <a href="mailto:hello@furab.app">hello@furab.app</a>. Expect a
        reply within a few days.
      </p>

      <h2>Reporting a problem</h2>
      <p>It helps enormously to include:</p>
      <ul>
        <li>Your iPhone model and iOS version</li>
        <li>What you tapped, and what happened instead of what you expected</li>
        <li>A screenshot, if the problem is visible</li>
      </ul>
      <p>
        Please do not send screenshots containing anything you would rather keep
        private — a description is usually enough.
      </p>

      <h2>Common questions</h2>

      <h3>My logs are not syncing to my partner&apos;s phone</h3>
      <p>
        Records sync through your private iCloud, so both phones must be signed
        in to the <strong>same Apple ID</strong> with iCloud Drive turned on.
        Two different Apple IDs cannot see each other&apos;s records — this is a
        consequence of keeping the data out of anyone else&apos;s hands,
        including ours.
      </p>

      <h3>Why is the Highlights card not writing anything?</h3>
      <p>
        Highlights are generated by Apple Intelligence on your device. Where it
        is unavailable, the app falls back to simple calculated summaries
        instead. Both work entirely offline.
      </p>

      <h3>Can I track more than one baby?</h3>
      <p>Not yet. It is the most requested addition, and it is being worked on.</p>

      <h3>How do I delete everything?</h3>
      <p>
        <strong>Settings → Reset All Data</strong> removes the profile and every
        log from your device and your iCloud. It cannot be undone.
      </p>
    </Prose>
  );
}
