import type { Metadata } from "next";
import { Prose } from "@/components/SiteChrome";

export const metadata: Metadata = {
  title: "Privacy — FURAB",
  description:
    "FURAB stores your baby's records on your device and in your own private iCloud. There is no FURAB server, no analytics and no advertising.",
};

export default function Privacy() {
  return (
    <Prose title="Privacy" updated="14 September 2026">
      <p>
        FURAB records something intimate: the feeds, nappies, sleep and
        medication of a newborn, and a mother&apos;s own meals and pumping. That
        information belongs to you. This page describes, plainly, where it goes.
      </p>

      <h2>There is no FURAB server</h2>
      <p>
        We do not run a backend. Your records are stored on your iPhone and
        synced through <strong>your own private iCloud database</strong>, under
        your Apple ID. We cannot read them, and neither can anyone else you
        have not shared your Apple ID with. Sync is handled by Apple&apos;s
        CloudKit and is governed by Apple&apos;s privacy policy.
      </p>

      <h2>Sign in with Apple</h2>
      <p>
        Signing in uses Apple&apos;s own flow. The app receives an anonymous
        user identifier, and your name only if you choose to share it. Both stay
        on your device. If you use Apple&apos;s Hide My Email, we never see a
        real address — and since there is no server, there is nowhere for one to
        be sent anyway.
      </p>

      <h2>Highlights are written on your device</h2>
      <p>
        The plain-language summaries on each tracker are generated by Apple
        Intelligence running locally on your iPhone. Your logs are not uploaded
        to us, to Apple, or to any AI provider in order to produce them. On
        devices without Apple Intelligence, the summaries are calculated by
        simple arithmetic on the device instead.
      </p>

      <h2>Photos</h2>
      <p>
        Photos you attach to a nappy, a medication or a meal are stored
        alongside the rest of your records, in your private iCloud. They are
        never uploaded anywhere else.
      </p>

      <h2>What we do not do</h2>
      <ul>
        <li>No analytics or crash-reporting SDKs</li>
        <li>No advertising, and no advertising identifiers</li>
        <li>No third-party trackers</li>
        <li>No selling or sharing of data, because we never receive any</li>
      </ul>

      <h2>Notifications</h2>
      <p>
        Feed and medication reminders are scheduled locally by your iPhone. They
        are not push notifications sent from a server, and their contents never
        leave your device.
      </p>

      <h2>Deleting your data</h2>
      <p>
        <strong>Settings → Reset All Data</strong> permanently deletes the baby
        profile and every log from the device and from your private iCloud.
        Deleting the app removes the local copy; records in your iCloud can also
        be removed in iOS Settings under your Apple ID.
      </p>

      <h2>Children</h2>
      <p>
        FURAB is used by an adult to record information about an infant. It is
        not designed for, or directed at, use by children. The records are
        entered by the parent or carer and remain under their control.
      </p>

      <h2>Changes</h2>
      <p>
        If this policy changes in a way that affects how your information is
        handled, the updated date above will change and the new terms will be
        described here.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about privacy: <a href="mailto:hello@furab.app">hello@furab.app</a>.
      </p>
    </Prose>
  );
}
